on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publicar versi贸n

jobs:
  build:
    name: Publicar versi贸n
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v2

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          # Directory containing source code (optional requirements.txt).
          path: src
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@0.1.4
        with:
          # Directory containing source code & .spec file (optional requirements.txt).
          path: src
      - name: Publicar versi贸n
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Versi贸n ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Subir .exe
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist/windows/calzador.exe
          asset_name: calzador.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Subir ELF
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist/linux/calzador
          asset_name: calzador_linux
          asset_content_type: application/x-executable
